### ISSUE TITLE
ext/apcu/php_apc.h: No such file or directory

### ISSUE THREAD

**Issue by ctrl-f5** [krakjoe/apcu-bc#1]
```
php_apc.c:33:30: fatal error: ext/apcu/php_apc.h: No such file or directory
 #include "ext/apcu/php_apc.h"
```

I've just installed APCu for php7, and am now trying to add this, but I'm getting the above error.

**Comment by remicollet** [comment]
You need APCu "master" which install this header.

**Comment by ctrl-f5** [comment]
aah ok, right, I have APCu 5.1.0 installed. switching to master solved the problem, thanks.

**Comment by sajidunnar** [comment]
---aah ok, right, I have APCu 5.1.0 installed. switching to master solved the problem, thanks.
Can you please explain ,  I Am getting same error 

  #include "ext/apcu/php_apc.h"                                                
           ^~~~~~~~~~~~~~~~~~~~                                                
  1 error generated.                                                           
  make: *** [php_apc.lo] Error 1                                               
  ERROR: `make' failed                                                         
                                                                               

install [--with-mariadb]

➜  ~   #include "ext/apcu/php_apc.h"                                                

➜  ~ pecl list
Installed packages, channel pecl.php.net:
=========================================
Package Version State
apcu    5.1.12  stable
geoip   1.1.1   beta
