### ISSUE TITLE
Warning: apc_clear_cache() expects exactly 1 parameter, 0 given

### ISSUE THREAD

**Issue by Drachenkaetzchen** [krakjoe/apcu-bc#10]
When using the bc module, I receive the following error:

`Warning: apc_clear_cache() expects exactly 1 parameter, 0 given`

According to the [PHP documentation](http://php.net/manual/en/function.apc-clear-cache.php), the parameter is optional.

**Comment by remicollet** [comment]
@felicitus thanks for the report, fix will be in 1.0.1

Please try with master

**Comment by Drachenkaetzchen** [comment]
It works fine now. Thank you for the quick fix!

**Comment by remicollet** [comment]
@krakjoe what do you think of a 1.0.1 release ?

**Comment by krakjoe** [comment]
OK with me, can u sort it or do I have too?

**Comment by remicollet** [comment]
@krakjoe I think everything is ready (package.xml in ae00d560460e4dde249b353007e3e40d18666098) but AFAIK, only "lead" can upload new release on pecl.
