### ISSUE TITLE
Extension doesn't load

### ISSUE THREAD

**Issue by rinu** [krakjoe/apcu-bc#12]
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/rauno/apcu-bc/modules/apc.so' - /home/rauno/apcu-bc/modules/apc.so: undefined symbol: zif_apcu_store in Unknown on line 0

**Comment by remicollet** [comment]
You need to load apcu.so
(and, on some downstream build, to load it "before" apc.so)

**Comment by nicodemuz** [comment]
I was facing a similar issue and adding apcu.so also did the trick for me:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-apcu-bc/apc.so' - dlopen(/usr/local/opt/php70-apcu-bc/apc.so, 9): Symbol not found: _zif_apcu_add
  Referenced from: /usr/local/opt/php70-apcu-bc/apc.so
  Expected in: flat namespace
 in /usr/local/opt/php70-apcu-bc/apc.so in Unknown on line 0
```
