### ISSUE TITLE
Building for homebrew

### ISSUE THREAD

**Issue by mcfedr** [krakjoe/apcu-bc#13]
Hi, I am trying to get this into the homebrew php repo.
Having problems because it needs to see the apcu headers to build and the only way I can get it do see them is by using `make install` on apcu, which causes problems with homebrews bottles

See my pull request: https://github.com/Homebrew/homebrew-php/pull/2719

I am just not entirely sure where to start to get the php build process to look for headers in another folder. Maybe you could point me in the right direction.

Thanks

**Comment by remicollet** [comment]
Of course... the "apcu" extension need to be installed....

Perhaps you can try to play with CFLAGS... no warranty.

**Comment by remicollet** [comment]
Perhaps you should look at how other dependent ext. are managed.

E.g. http depends on raphf and propro  https://github.com/Homebrew/homebrew-php/blob/master/Formula/php56-http.rb

**Comment by mcfedr** [comment]
Ah, interesting, I had flicked though looking for something like that. Ill give it a go.
