### ISSUE TITLE
Segfault with apc_inc and PHP7

### ISSUE THREAD

**Issue by szicsu** [krakjoe/apcu-bc#14]
Example:
`php -r 'apc_inc("foo");'`

Info:
`Program received signal SIGSEGV, Segmentation fault.`
`apc_cache_busy (cache=cache@entry=0x0) at /opt/apcu/apcu-5.1.3/apc_cache.c:1748`
`1748       return (cache->header->state & APC_CACHE_ST_BUSY);`

System info:

> APC Compatibility => 1.0.2
> APCu Version => 5.1.3
> PHP 7.0.3-1~dotdeb+8.1 (cli) ( NTS )
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

If I enable the apc, then I don't get segfault:
`php -d 'apc.enable_cli=1' -r 'apc_inc("foo");'`

**Comment by remicollet** [comment]
Can you please check if master fix this issue ?

**Comment by szicsu** [comment]
Thank you! The fix is working :)
