### ISSUE TITLE
Fast CGI exits with fatal error 0xC0000005

### ISSUE THREAD

**Issue by tomolimo** [krakjoe/apcu-bc#17]
Hello,
When using GLPi 9.1 RC2 with PHP 7.0.9 and APC + APCu (i.e. apcu-bc ) on my IIS 8 (Windows 2012 R2), I get from times to times an HTTP 500 Internal server error.

I got apcu-bc from: http://pecl.php.net/package/apcu_bc/1.0.3/windows and it seems to be still in beta status...

I've activated the "failed request tracing" and found only the error code: 

> ModuleName="FastCgiModule", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="500", HttpReason="Internal Server Error", HttpSubStatus="0", ErrorCode="3221225477 (0xC0000005)", ConfigExceptionInfo=""

And the the event viewer the error message is:

> Faulting application name: php-cgi.exe, version: 7.0.9.0, time stamp: 0x578fb9d9
> Faulting module name: php_apcu.dll, version: 7.0.5.0, time stamp: 0x5756cd47
> Exception code: 0xc0000005
> Fault offset: 0x0000000000002b80
> Faulting process id: 0x10e8
> Faulting application start time: 0x01d1ed657e540797
> Faulting application path: C:\Program Files\PHP\v7.0\php-cgi.exe
> Faulting module path: C:\Program Files\PHP\v7.0\ext\php_apcu.dll

Of course if I disable the apc/apcu modules, the error doesn't appear.
Here is the apc/apcu configuration:

> apc
> APC Compatibility  1.0.3  
> APCu Version  5.1.2  
> Build Date  Feb 11 2016 17:35:43  
> 
> apcu
> APCu Support Enabled 
> Version  5.1.5  
> APCu Debugging  Disabled  
> MMAP Support  Disabled  
> Serialization Support  php  
> Build Date  Jun 7 2016 15:32:13  
> Directive Local Value 
> apc.coredump_unmap Off 
> apc.enable_cli Off 
> apc.enabled On 
> apc.entries_hint 0 
> apc.gc_ttl 0  
> apc.preload_path l:/temp/  
> apc.serializer php 
> apc.shm_segments 1
> apc.shm_size 128M 
> apc.slam_defense Off 
> apc.smart 0  
> apc.ttl 0  
> apc.use_request_time Off 
> apc.writable l:/temp/

Thank you for your help
Regards,
Tomolimo

**Comment by Pes8** [comment]
I have the same issue (on IIS 8 -Windows 2012 R2 - PHP 7.0.7 - apcu 5.1.5 )

Some times it happen the 500 error message (randomly ~50% times), of course if I turn off apcu cache this strange behavior disappear.

Temporary I fixed it forcing Fast-CGI max_instances to 1

**Comment by tomolimo** [comment]
Hello,
If I do the same setting (i.e. Fast-CGI max_instances to 1), then it's also OK.
This is of course a workaround, but not a real fix.
I hope it will be fixed ASAP, as we are waiting for that to use it with GLPi (https://github.com/glpi-project/glpi)
regards,
Tomolimo

**Comment by krakjoe** [comment]
You should not expect apc to work when you are running in an (F)CGI SAPI that does not use a fork based processing model.
