### ISSUE TITLE
Perf implications

### ISSUE THREAD

**Issue by staabm** [krakjoe/apcu-bc#19]
Do you have any benchmarks or number on the performance of this BC layer?

Should people upgrading from phps' native apc implementation preferrable upgrade to apcu functions instead? Or is the overhead nearly not existent?

**Comment by krakjoe** [comment]
There is no appreciable difference; This layer calls the same internal (to apc) functions that APCu does, but just accepts the old parameters, the only meaningful difference is prototypes and names of functions.
