### ISSUE TITLE
Does this extension provide support for apc.rfc1867 (for a file upload progress bar)

### ISSUE THREAD

**Issue by ghost** [krakjoe/apcu-bc#22]
I've successfully installed 1.0.3 against PHP 7.0.16 and phpinfo() shows both apcu and apc as loaded, as follows:
apc
----
APC Compatibility 	1.0.3
APCu Version 	5.1.8
Build Date 	Feb 16 2017 19:19:59 

What neither it nor the apcu section  shows however are the apc.rfc1867 values (as apcu 4.0.10 did in PHP 5.6)

And when trying to run our code against this PHP implementation I see:

PHP initialisation variable apc.rfc1867 must be set to 1

but the rfc1867 related values are set as follows in our php.ini (in the same way as they have always been set and worked)

apc.rfc1867=1
apc.rfc1867_freq=0

Am I doing something wrong or is the - very sad - reality that we will have to use some other mechanism for providing a file upload progress bar (I tried using session.upload_progress and found it nowhere near as robust as apc)

I would greatly appreciate it if you could let me know - thanks!

**Comment by remicollet** [comment]
Upload progess are now a native PHP feature.
http://php.net/manual/en/session.upload-progress.php

So old APC feature is not available in this extension

**Comment by ghost** [comment]
Read my comment above: because of the complete lack of feedback here, we tried replacing apc with the new session.upload_progress. The design is flawed as it it does not work with database sessions - rendering it unusable. See here for more information: https://bugs.php.net/bug.php?id=74131
