### ISSUE TITLE
Create a stable 1.0.4 release?

### ISSUE THREAD

**Issue by TysonAndre** [krakjoe/apcu-bc#25]
There have been 0 changes (apart from documentation and travis changes) to this extension since 2016-02-11, so I'd consider this stable.

Can a 1.0.4 release be created that's marked as stable for PECL (but identical to 1.0.3 otherwise?)

- i.e. change `  <release>beta</release>` to `  <release>stable</release>` in the next release

This will solve the root cause of #24

**Comment by Nirjonadda** [comment]
@TysonAndre When happen the 1.0.4 stable release?

**Comment by Nirjonadda** [comment]
@remicollet Updated to APCu 5.1.9 but Version no are not updated.

https://image.prntscr.com/image/CW5vKTjeQuezrVEVF_Qiog.png

**Comment by Nirjonadda** [comment]
@remicollet @krakjoe Do you have any plan 1.0.4 stable release?

**Comment by remicollet** [comment]
1.0.4 is released.
