### ISSUE TITLE
Release 1.0.5

### ISSUE THREAD

**Issue by DaveRandom** [krakjoe/apcu-bc#28]
Please can a release be tagged that includes the new commits since 1.0.4.

1.0.4 does not pass our internal CI so I cannot make a release from it, which means I cannot release an image for 7.3.0b1 unless I use a ref that is not a tag - I don't really want to do that, so if you could create a tag that would be appreciated.

(N.B. although the same problems that cause failures were present in 7.2, previously our CI was passing because it was not set up correctly, but [this](https://github.com/php/php-src/commit/f46da1da7ddc1af2395868eb6dcfc02a96c83396#diff-b6bbbff6a2dad1c77f0f1680692cd1be) change has "broken" our builds)

**Comment by DaveRandom** [comment]
@remicollet if you could see your way to creating a release of this alongside apcu (as ref'd above) I would be very grateful :-)

**Comment by remicollet** [comment]
1.0.5 released
