### ISSUE TITLE
Can't compile with PHP 7.4

### ISSUE THREAD

**Issue by cmb69** [krakjoe/apcu-bc#32]
Due to https://github.com/php/php-src/commit/bebcdcc74573b015c22238dbc9b2698c88b7a601.

**Comment by remicollet** [comment]
I don't see any uint/ulong usage here ?
Can you open a PR ?

**Comment by cmb69** [comment]
Ah, indeed, that was an issue with APCu, and already fixed with APCu 5.1.8. I've updated that and are re-building now. Sorry for the noise.
