### ISSUE TITLE
Consider adding a composer.json for pickle?

### ISSUE THREAD

**Issue by shouze** [krakjoe/apcu-bc#7]
This would looks like:

``` json
{
    "name": "apcu_bc",
    "version": "1.0.1-beta",
    "type": "extension",
    "license": [
        "PHP License"
    ],
    "authors": [
        {
            "name": "Joe Watkins",
            "email": "krakjoe@php.net"
        },
        {
            "name": "Remi Collet",
            "email": "remi@php.net"
        }
    ],
    "description": "APCu Backwards Compatibility Module"
}
```

**Comment by remicollet** [comment]
Shouldn't the dependency on "apcu" be described in this file ?

**Comment by shouze** [comment]
@remicollet you're probably right yes :+1: 

So, something looking like that instead? (ping @pierrejoye)

``` json
{
    "name": "apcu_bc",
    "version": "1.0.1-beta",
    "type": "extension",
    "license": [
        "PHP License"
    ],
    "require": {
        "ext-apcu": "~5.1"
    },
    "authors": [
        {
            "name": "Joe Watkins",
            "email": "krakjoe@php.net"
        },
        {
            "name": "Remi Collet",
            "email": "remi@php.net"
        }
    ],
    "description": "APCu Backwards Compatibility Module"
}
```

**Comment by krakjoe** [comment]
any chance of a PR ??

it might be good if there were a step in travis to test this and pecl builds actually ... the thought just occurred to me.

@remicollet what do you think, should we add pecl/pickle to travis too ?

I'm off out to a meetup tonight, if you put a PR for composer.json in, it can be merged by remi if I'm not here ...

**Comment by remicollet** [comment]
Hmm... adding "pecl package ; pecl install -f /path/to/foo.tgz' can have sense... never saw this in  any project

**Comment by krakjoe** [comment]
I break pecl builds a lot ... I think we should go for it ... let's wait to see if this issue is actioned, and we can add pickle at the same time ...

**Comment by shouze** [comment]
Yes for a PR guys, no tonight but tomorow
