### ISSUE TITLE
Extension doesn't load

### ISSUE THREAD

**Issue by crisbarros** [krakjoe/apcu-bc#9]
I got this error after successfully compiling:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/apc.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/apc.so: undefined symbol: zif_apcu_store in Unknown on line 0

I'm using PHP 7.0.0:
PHP Api Version:         20151012

**Comment by krakjoe** [comment]
You have apcu loaded ?

**Comment by marc-mabe** [comment]
I have the same error on travis - see https://travis-ci.org/marc-mabe/zend-cache/jobs/98016459

It's installing first apcu and then apcu_bc using `pecl install`

**Comment by kimjuan** [comment]
I set the priority of apc after apcu and it is working.

```
lrwxrwxrwx 1 root root   31 Jan  2 17:53 20-apcu.ini -> /etc/php/mods-available/apcu.ini
lrwxrwxrwx 1 root root   31 Jan  2 17:53 21-apc.ini -> /etc/php/mods-available/apc.ini
```

**Comment by remicollet** [comment]
Related to downstream using dlopen(RTLD_NOW).
So, yes, extension ini file name  have to be managed to ensure correct load order.
